---

pkcs12_file:     /path/to/cert.p12
pkcs12_password: 1234
OrgNr:           123456789012
BestallningsId:  00001234-FO01-1234

logdir: /etc/koha/sites/mykoha/navet2koha/

socsec_attribute: PNR
protected_attribute: SKYDDAD

patronmap:
    firstname: './Personpost/Namn/Fornamn'
    surname:   './Personpost/Namn/Efternamn'
    address:   './Personpost/Adresser/Folkbokforingsadress/Utdelningsadress2'
    zipcode:   './Personpost/Adresser/Folkbokforingsadress/PostNr'
    city:      './Personpost/Adresser/Folkbokforingsadress/Postort'
